import { type UserData } from "@shared/schema";
import { randomUUID } from "crypto";

// Helper to generate transaction ID
const generateId = () => randomUUID();

// Helper to generate date in the past
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// User database - easily editable for balances and adding new users
export const users: Record<string, UserData> = {
  "john.smith": {
    password: "mypassword123",
    name: "John Smith",
    accounts: [
      {
        id: "acc-js-1",
        type: "Private Account",
        iban: "CH5604835012345678000",
        balance: 1850000,
        currency: "CHF",
        performanceChange: 1.20,
      },
      {
        id: "acc-js-2",
        type: "Savings Account",
        iban: "CH3108339000987654321",
        balance: 3200000,
        currency: "CHF",
        performanceChange: 2.15,
      },
      {
        id: "acc-js-3",
        type: "Investment Portfolio",
        iban: "CH4487890123456789001",
        balance: 7450000,
        currency: "CHF",
        performanceChange: 5.80,
      },
    ],
    transactions: [
      // Private Account - Daily Charges
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "incoming",
        amount: 15000,
        counterpartyName: "Salary - Tech Corp AG",
        counterpartyIban: "CH9300762011623852957",
        reference: "Monthly salary December 2024",
        date: daysAgo(2),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "outgoing",
        amount: 2500,
        counterpartyName: "Rent Payment",
        counterpartyIban: "CH1234567890123456789",
        reference: "Apartment rent December",
        date: daysAgo(5),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "outgoing",
        amount: 89.50,
        counterpartyName: "Coop Supermarket",
        counterpartyIban: "CH8912345678901234567",
        reference: "Groceries",
        date: daysAgo(1),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "outgoing",
        amount: 145,
        counterpartyName: "Swisscom AG",
        counterpartyIban: "CH1200762011623852957",
        reference: "Mobile & Internet subscription",
        date: daysAgo(3),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "outgoing",
        amount: 62.40,
        counterpartyName: "Restaurant Avalon",
        counterpartyIban: "CH3332211043210987654",
        reference: "Dinner reservation",
        date: daysAgo(4),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-1",
        type: "outgoing",
        amount: 120,
        counterpartyName: "Spotify Premium",
        counterpartyIban: "CH4543210987654321098",
        reference: "Music streaming subscription",
        date: daysAgo(6),
        fee: 0,
      },
      // Savings Account - Monthly Additions from Private
      {
        id: generateId(),
        accountId: "acc-js-2",
        type: "incoming",
        amount: 5000,
        counterpartyName: "Transfer from Private Account",
        counterpartyIban: "CH5604835012345678000",
        reference: "Monthly savings transfer",
        date: daysAgo(1),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-2",
        type: "incoming",
        amount: 3400,
        counterpartyName: "Interest Payment - Monthly",
        counterpartyIban: "CH3108339000987654321",
        reference: "2.15% annual interest",
        date: daysAgo(10),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-2",
        type: "incoming",
        amount: 5000,
        counterpartyName: "Transfer from Private Account",
        counterpartyIban: "CH5604835012345678000",
        reference: "Monthly savings transfer",
        date: daysAgo(30),
        fee: 0,
      },
      // Investment Portfolio - Stock & Crypto Trading
      {
        id: generateId(),
        accountId: "acc-js-3",
        type: "outgoing",
        amount: 125000,
        counterpartyName: "Tesla Inc. Stock Purchase",
        counterpartyIban: "CH9876543210987654321",
        reference: "2500 shares @ CHF 50",
        date: daysAgo(3),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-3",
        type: "incoming",
        amount: 45000,
        counterpartyName: "Dividend Payment - Nestlé",
        counterpartyIban: "CH9876543210987654321",
        reference: "Dividend distribution Q4 2024",
        date: daysAgo(7),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-3",
        type: "outgoing",
        amount: 85000,
        counterpartyName: "Bitcoin Purchase",
        counterpartyIban: "CH5555666677778888999",
        reference: "2.5 BTC @ CHF 34000",
        date: daysAgo(12),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-js-3",
        type: "incoming",
        amount: 12500,
        counterpartyName: "Stock Sale - Microsoft",
        counterpartyIban: "CH9876543210987654321",
        reference: "500 shares sold @ CHF 25",
        date: daysAgo(20),
        fee: 0,
      },
    ],
  },

  "alexander.weber": {
    password: "123456",
    name: "Alexander Weber",
    accounts: [
      {
        id: "acc-aw-1",
        type: "Private Account",
        iban: "CH9300762011623852957",
        balance: 2750000,
        currency: "CHF",
        performanceChange: 0.85,
      },
      {
        id: "acc-aw-2",
        type: "Savings Account",
        iban: "CH5789012345678901234",
        balance: 4100000,
        currency: "CHF",
        performanceChange: 2.15,
      },
      {
        id: "acc-aw-3",
        type: "Investment Portfolio",
        iban: "CH2345678901234567890",
        balance: 8900000,
        currency: "CHF",
        performanceChange: 6.45,
      },
    ],
    transactions: [
      // Private Account - Daily Charges
      {
        id: generateId(),
        accountId: "acc-aw-1",
        type: "incoming",
        amount: 25000,
        counterpartyName: "Consulting Fee",
        counterpartyIban: "CH1111222233334444555",
        reference: "November consulting services",
        date: daysAgo(3),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-1",
        type: "outgoing",
        amount: 8500,
        counterpartyName: "Luxury Car Payment",
        counterpartyIban: "CH6666777788889999000",
        reference: "Mercedes lease December",
        date: daysAgo(10),
        fee: 12,
      },
      {
        id: generateId(),
        accountId: "acc-aw-1",
        type: "outgoing",
        amount: 245.80,
        counterpartyName: "Michelin Restaurant",
        counterpartyIban: "CH2211334455667788990",
        reference: "Fine dining experience",
        date: daysAgo(2),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-1",
        type: "outgoing",
        amount: 1200,
        counterpartyName: "Art Gallery Purchase",
        counterpartyIban: "CH3322445566778899001",
        reference: "Contemporary artwork",
        date: daysAgo(5),
        fee: 0,
      },
      // Savings Account - Monthly Additions
      {
        id: generateId(),
        accountId: "acc-aw-2",
        type: "incoming",
        amount: 10000,
        counterpartyName: "Transfer from Private Account",
        counterpartyIban: "CH9300762011623852957",
        reference: "Monthly savings transfer",
        date: daysAgo(1),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-2",
        type: "incoming",
        amount: 3500,
        counterpartyName: "Interest Payment",
        counterpartyIban: "CH5789012345678901234",
        reference: "Quarterly interest 2.15%",
        date: daysAgo(15),
        fee: 0,
      },
      // Investment Portfolio - Stock & Crypto
      {
        id: generateId(),
        accountId: "acc-aw-3",
        type: "outgoing",
        amount: 200000,
        counterpartyName: "Google Stock Purchase",
        counterpartyIban: "CH2345678901234567890",
        reference: "1500 shares @ CHF 133.33",
        date: daysAgo(2),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-3",
        type: "incoming",
        amount: 125000,
        counterpartyName: "Portfolio Growth",
        counterpartyIban: "CH2345678901234567890",
        reference: "Q4 asset appreciation",
        date: daysAgo(20),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-3",
        type: "outgoing",
        amount: 150000,
        counterpartyName: "Ethereum Purchase",
        counterpartyIban: "CH5555666677778888999",
        reference: "100 ETH @ CHF 1500",
        date: daysAgo(8),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-aw-3",
        type: "incoming",
        amount: 45000,
        counterpartyName: "Dividend Payment - Apple",
        counterpartyIban: "CH2345678901234567890",
        reference: "Dividend distribution Dec 2024",
        date: daysAgo(18),
        fee: 0,
      },
    ],
  },

  "marina.berger": {
    password: "secret2025",
    name: "Marina Berger",
    accounts: [
      {
        id: "acc-mb-1",
        type: "Private Account",
        iban: "CH4208704048075000000",
        balance: 3650000,
        currency: "CHF",
      },
      {
        id: "acc-mb-2",
        type: "Savings Account",
        iban: "CH7604835012345678999",
        balance: 5200000,
        currency: "CHF",
      },
      {
        id: "acc-mb-3",
        type: "Investment Portfolio",
        iban: "CH3609000000000000001",
        balance: 12500000,
        currency: "CHF",
      },
    ],
    transactions: [
      {
        id: generateId(),
        accountId: "acc-mb-1",
        type: "incoming",
        amount: 35000,
        counterpartyName: "Director Salary",
        counterpartyIban: "CH9999888877776666555",
        reference: "Executive compensation December",
        date: daysAgo(1),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-mb-1",
        type: "outgoing",
        amount: 15000,
        counterpartyName: "Private School Tuition",
        counterpartyIban: "CH1234509876543210987",
        reference: "Winter semester fees",
        date: daysAgo(6),
        fee: 12,
      },
      {
        id: generateId(),
        accountId: "acc-mb-3",
        type: "incoming",
        amount: 280000,
        counterpartyName: "Real Estate Income",
        counterpartyIban: "CH7777666655554444333",
        reference: "Property rental Q4 2024",
        date: daysAgo(12),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-mb-2",
        type: "incoming",
        amount: 5600,
        counterpartyName: "Savings Interest",
        counterpartyIban: "CH7604835012345678999",
        reference: "Annual interest payment",
        date: daysAgo(18),
        fee: 0,
      },
    ],
  },

  "thomas.mueller": {
    password: "password123",
    name: "Thomas Müller",
    accounts: [
      {
        id: "acc-tm-1",
        type: "Private Account",
        iban: "CH1234567890123456789",
        balance: 890000,
        currency: "CHF",
      },
      {
        id: "acc-tm-2",
        type: "Savings Account",
        iban: "CH9876543210987654321",
        balance: 1450000,
        currency: "CHF",
      },
      {
        id: "acc-tm-3",
        type: "Investment Portfolio",
        iban: "CH5555444433332222111",
        balance: 3850000,
        currency: "CHF",
      },
    ],
    transactions: [
      {
        id: generateId(),
        accountId: "acc-tm-1",
        type: "incoming",
        amount: 12000,
        counterpartyName: "Freelance Project",
        counterpartyIban: "CH1111222233334444555",
        reference: "Web development November",
        date: daysAgo(4),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-tm-1",
        type: "outgoing",
        amount: 3200,
        counterpartyName: "Mortgage Payment",
        counterpartyIban: "CH9999000011112222333",
        reference: "Monthly mortgage December",
        date: daysAgo(8),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-tm-3",
        type: "incoming",
        amount: 18500,
        counterpartyName: "Stock Dividends",
        counterpartyIban: "CH5555444433332222111",
        reference: "Quarterly dividend payout",
        date: daysAgo(14),
        fee: 0,
      },
    ],
  },

  "sophie.laurent": {
    password: "secure456",
    name: "Sophie Laurent",
    accounts: [
      {
        id: "acc-sl-1",
        type: "Private Account",
        iban: "CH6789012345678901234",
        balance: 4250000,
        currency: "CHF",
      },
      {
        id: "acc-sl-2",
        type: "Savings Account",
        iban: "CH3456789012345678901",
        balance: 6800000,
        currency: "CHF",
      },
      {
        id: "acc-sl-3",
        type: "Investment Portfolio",
        iban: "CH8901234567890123456",
        balance: 15200000,
        currency: "CHF",
      },
    ],
    transactions: [
      {
        id: generateId(),
        accountId: "acc-sl-1",
        type: "incoming",
        amount: 45000,
        counterpartyName: "Business Profits",
        counterpartyIban: "CH2222333344445555666",
        reference: "Q4 company distribution",
        date: daysAgo(5),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-sl-1",
        type: "outgoing",
        amount: 28000,
        counterpartyName: "Luxury Travel",
        counterpartyIban: "CH7777888899990000111",
        reference: "Maldives vacation package",
        date: daysAgo(9),
        fee: 25,
      },
      {
        id: generateId(),
        accountId: "acc-sl-3",
        type: "incoming",
        amount: 320000,
        counterpartyName: "Investment Gains",
        counterpartyIban: "CH8901234567890123456",
        reference: "Portfolio rebalancing profit",
        date: daysAgo(16),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-sl-2",
        type: "incoming",
        amount: 7300,
        counterpartyName: "Interest Earnings",
        counterpartyIban: "CH3456789012345678901",
        reference: "Semi-annual interest",
        date: daysAgo(22),
        fee: 0,
      },
    ],
  },

  "david.zhang": {
    password: "banking789",
    name: "David Zhang",
    accounts: [
      {
        id: "acc-dz-1",
        type: "Private Account",
        iban: "CH1111222233334444555",
        balance: 1920000,
        currency: "CHF",
      },
      {
        id: "acc-dz-2",
        type: "Savings Account",
        iban: "CH6666777788889999000",
        balance: 2850000,
        currency: "CHF",
      },
      {
        id: "acc-dz-3",
        type: "Investment Portfolio",
        iban: "CH3333222211110000999",
        balance: 6750000,
        currency: "CHF",
      },
    ],
    transactions: [
      {
        id: generateId(),
        accountId: "acc-dz-1",
        type: "incoming",
        amount: 22000,
        counterpartyName: "Tech Startup Salary",
        counterpartyIban: "CH4444555566667777888",
        reference: "CTO compensation December",
        date: daysAgo(3),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-dz-1",
        type: "outgoing",
        amount: 5500,
        counterpartyName: "Office Lease",
        counterpartyIban: "CH9999888877776666555",
        reference: "Co-working space monthly",
        date: daysAgo(11),
        fee: 12,
      },
      {
        id: generateId(),
        accountId: "acc-dz-3",
        type: "incoming",
        amount: 95000,
        counterpartyName: "Crypto Profits",
        counterpartyIban: "CH3333222211110000999",
        reference: "Digital asset trading gains",
        date: daysAgo(17),
        fee: 0,
      },
      {
        id: generateId(),
        accountId: "acc-dz-2",
        type: "incoming",
        amount: 3050,
        counterpartyName: "Savings Interest",
        counterpartyIban: "CH6666777788889999000",
        reference: "Quarterly interest 2.15%",
        date: daysAgo(25),
        fee: 0,
      },
    ],
  },
};
